### ISSUE TITLE
can't use skip intro addon

### ISSUE THREAD

**Issue by ghost** [aenemapy/aenemapyrepo#27] opened 2021-08-02 20:12 UTC

**Comment by DaisyF8** [comment] 2021-11-26 14:08
No PR from the dev on Reddit who updated this addon to Py3 ?

**Comment by peno64** [comment] 2021-11-26 19:33
@DaisyF8 
I adapted the addon ezmaintenanceplus from this repo, but only this addon. The repo contains several other addons.

Your description "can't use skip intro addon" is really too less information to be able to help you.
It's as if you are saying "my vehicle doesn't work anymore" What can someone say on such a statement?

**Comment by DaisyF8** [comment] 2021-11-26 21:43
Yeah but you're wrong. I didn't open this issue, @ghost did so many months ago.  Look at the first comment, it got deleted.  I didn't want to open a new issue to write my question.  I'm assuming the addon stopped working when Kodi 19 went python 3, seems reasonable to think so.

And some hours ago u/iDuts on Reddit r/addons4kodi said he rewrote the skip intro addon for Py3. But he just gave a seperate zip,  while u/a3n3ma asked him to possibly push it here so it could be in the repo.

So does that clear things up ? My question was more directed towards @aenemapy anyway.

**Comment by zDuts** [comment] 2021-11-27 12:28
i've made a pull request couple minutes ago. Hope that helps with this ticket.

**Comment by DaisyF8** [comment] 2021-11-27 12:35
Hey awesome :D and thx for updating it.

**Comment by peno64** [comment] 2021-11-27 14:25
That is nice. The problem is that aenemapy doesn't react anymore so your pull request won't get merged...

**Comment by zDuts** [comment] 2021-11-27 14:31
@peno64 he did react on reddit so should be fine.
https://www.reddit.com/r/Addons4Kodi/comments/r27suc/release_for_v19_updated_old_skip_intro_addon_for/
Not sure if i should repackage the zips.
I updated hideosd too btw

**Comment by aenemapy** [comment] 2021-12-03 16:36
all good, thanks zDuts for his support. all credit goes to him for the port

**Closed as completed by aenemapy** 2021-12-03 16:36 UTC
